language: node_js
node_js:
  - "stable"
cache:
  directories:
  - website/node_modules
script:
  - cd website && yarn && yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  target_branch: gh-pages
  keep_history: true
  local_dir: website/build/twasi-docs
  on:
    branch: master
